#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the portfolio app.
# Runs after checkout. Prepares the pinned Bun toolchain, project
# dependencies, a git-ignored local .env, and a seeded local SQLite DB.
set -euo pipefail

BUN_VERSION="1.3.14"
export BUN_INSTALL="${HOME}/.bun"

# 1. Install the pinned Bun toolchain when missing or on the wrong version.
if ! command -v bun >/dev/null 2>&1 || [ "$(bun --version 2>/dev/null || true)" != "${BUN_VERSION}" ]; then
  curl -fsSL https://bun.sh/install | bash -s "bun-v${BUN_VERSION}"
fi

# Make Bun discoverable for install/start/terminals without relying on shell profiles.
export PATH="${BUN_INSTALL}/bin:${PATH}"
if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
  sudo ln -sf "${BUN_INSTALL}/bin/bun" /usr/local/bin/bun
  sudo ln -sf "${BUN_INSTALL}/bin/bunx" /usr/local/bin/bunx
fi

bun --version

# 2. Install dependencies from the committed lockfile.
bun install --frozen-lockfile

# 3. Create a git-ignored local dev .env only when absent (preserve user edits).
#    Uses a local SQLite file so no external Turso/secret is needed for dev.
if [ ! -f .env ]; then
  CMS_TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > .env <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
# Local SQLite keeps dev self-contained; no external secrets required.
# The API defaults CORS to localhost, so only these three are needed for dev.
# Add optional keys (UPLOADTHING_TOKEN, GITHUB_TOKEN, YOUTUBE_API_KEY, Mayar,
# Resend) as Cloud Agent secrets to exercise those features.
DATABASE_URL=file:./dev.sqlite
API_PORT=3001
CMS_ADMIN_TOKEN=${CMS_TOKEN}
EOF
fi

# 4. Apply the Drizzle schema and seed sample content (all idempotent upserts).
bun run db:push
bun run db:seed
bun run db:seed:testimonials
bun run db:seed:speaking
bun run db:seed:coupons

echo "[install] Cloud Agent environment ready."
