#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the portfolio app.
# Runs after checkout. Prepares the pinned Bun toolchain, project
# dependencies, a git-ignored local .env, and — only for a local SQLite
# file — a pushed and seeded dev database.
set -euo pipefail

BUN_VERSION="1.3.14"
export BUN_INSTALL="${HOME}/.bun"

# 1. Install the pinned Bun toolchain when missing or on the wrong version.
if ! command -v bun >/dev/null 2>&1 || [ "$(bun --version 2>/dev/null || true)" != "${BUN_VERSION}" ]; then
  curl -fsSL https://bun.sh/install | bash -s "bun-v${BUN_VERSION}"
fi

# Make Bun discoverable for install/start/terminals without relying on shell profiles.
export PATH="${BUN_INSTALL}/bin:${PATH}"
if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
  sudo ln -sf "${BUN_INSTALL}/bin/bun" /usr/local/bin/bun
  sudo ln -sf "${BUN_INSTALL}/bin/bunx" /usr/local/bin/bunx
fi

bun --version

# 2. Install dependencies from the committed lockfile.
bun install --frozen-lockfile

# 3. Write a git-ignored local dev .env only when absent (preserve user edits).
#    Injected environment variables (e.g. Cloud Agent secrets) always take
#    precedence because the app loads config with dotenv, which does not
#    override values already present in the environment. This .env only supplies
#    fallbacks — most importantly a local SQLite URL so dev is self-contained
#    when no database secret is configured.
if [ ! -f .env ]; then
  CMS_TOKEN="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  cat > .env <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
# Fallbacks only; any matching environment variable / secret overrides these.
# Add optional keys (UPLOADTHING_TOKEN, GITHUB_TOKEN, YOUTUBE_API_KEY, Mayar,
# Resend) as Cloud Agent secrets to exercise those features.
DATABASE_URL=file:./dev.sqlite
API_PORT=3001
CMS_ADMIN_TOKEN=${CMS_TOKEN}
EOF
fi

# 4. Apply the Drizzle schema and seed sample content ONLY when the effective
#    database is a local SQLite file. If DATABASE_URL points at a remote
#    database (e.g. a Turso libsql:// URL provided via a secret), skip these
#    steps so environment setup never mutates a real/production database.
EFFECTIVE_DB_URL="${DATABASE_URL:-file:./dev.sqlite}"
case "${EFFECTIVE_DB_URL}" in
  file:*)
    echo "[install] Bootstrapping local SQLite dev database: ${EFFECTIVE_DB_URL}"
    export DATABASE_URL="${EFFECTIVE_DB_URL}"
    export DATABASE_AUTH_TOKEN=""
    bun run db:push
    bun run db:seed
    bun run db:seed:testimonials
    bun run db:seed:speaking
    bun run db:seed:coupons
    ;;
  *)
    echo "[install] DATABASE_URL is a non-local database provided via the environment."
    echo "[install] Skipping db:push/seed so setup does not mutate it. The dev server will use it as configured."
    ;;
esac

echo "[install] Cloud Agent environment ready."
